version: "3"

# TODO - move all secrets to .env file in production
services:
  db:
    image: postgres
    container_name: travelio_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=travelio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=9hpD54^2J:f<6
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: travelio_web
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             coverage run manage.py test &&
             python manage.py createadmin &&
             python manage.py runserver --insecure 0.0.0.0:8000"
    environment:
      - SECRET_KET=8n)1l-4#54lb6cxik-@qmztwy^#8^167ou%_7-odw-y2e4#o%%
      - DEBUG=False
      - POSTGRES_DB=travelio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=9hpD54^2J:f<6
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy