# Generated by Django 4.0.2 on 2022-02-24 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_mates',
            field=models.ManyToManyField(blank=True, help_text='Choose who is going with you', related_name='mates', to=settings.AUTH_USER_MODEL),
        ),
    ]
