# Generated by Django 4.0.2 on 2022-02-25 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_trip_user_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='descriptions',
            new_name='description',
        ),
    ]
