# Generated by Django 4.0.2 on 2022-02-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_rename_descriptions_destination_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='destinations',
            field=models.ManyToManyField(blank=True, help_text='Add destinations to your trip', related_name='destinations', to='travel.Destination'),
        ),
    ]
