# Generated by Django 4.0.2 on 2022-02-25 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_trip_destinations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='trip',
            field=models.OneToOneField(help_text='Link Budget item to any trip', on_delete=django.db.models.deletion.CASCADE, to='travel.trip'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='budget',
            field=models.ForeignKey(help_text='Parent budget', on_delete=django.db.models.deletion.CASCADE, to='travel.budget'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='item_price',
            field=models.FloatField(default=0, help_text='Price for item per 1 quantity'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='label',
            field=models.CharField(help_text='Name for the expence', max_length=50),
        ),
    ]
