# Generated by Django 4.0.2 on 2022-02-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Recommended size: 1080x1080px', max_length=255, null=True, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Max length: 120 symbols', max_length=120, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(help_text='Max length: 80 sumbols', max_length=80, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Max length: 80 symbols', max_length=120, verbose_name='Password'),
        ),
    ]
